window.products = [
  {
    id: "samsung-55-du7000",
    brand: "Samsung",
    model: "UA55DU7000",
    fullName: "Smart Tivi Samsung 4K 55 inch UA55DU7000",
    size: "55 inch",
    type: "Tivi mới",
    condition: "Mới",
    warranty: "Bảo hành chính hãng",
    features: ["4K UHD", "Smart TV", "Bảo hành chính hãng"],
    oldPrice: "",
    price: "Liên hệ nhận giá tốt",
    image: "",
    images: [],
    badge: "Hàng mới",
    description: "Phù hợp phòng khách, hình ảnh sắc nét, dễ sử dụng.",
  },
  {
    id: "lg-50-4k-uhd",
    brand: "LG",
    model: "LG 4K UHD 50 inch",
    fullName: "Smart Tivi LG 4K UHD 50 inch",
    size: "50 inch",
    type: "Tivi mới",
    condition: "Mới",
    warranty: "Bảo hành theo chính sách hãng",
    features: ["Độ phân giải 4K UHD", "Hình ảnh sáng, màu sắc cân bằng", "Tư vấn theo diện tích phòng"],
    oldPrice: "",
    price: "Giá đang cập nhật",
    image: "",
    images: [],
    badge: "Tư vấn nhiều",
    description: "Lựa chọn phù hợp cho gia đình cần tivi 4K kích thước vừa, dễ bố trí trong phòng khách hoặc phòng sinh hoạt chung.",
  },
  {
    id: "sony-65-google-tv",
    brand: "Sony",
    model: "Sony Google TV 65 inch",
    fullName: "Google Tivi Sony 4K 65 inch",
    size: "65 inch",
    type: "Tivi mới",
    condition: "Mới",
    warranty: "Bảo hành theo chính sách hãng",
    features: ["Google TV tiện lợi", "Gợi ý cho không gian rộng", "Trải nghiệm giải trí phong phú"],
    oldPrice: "",
    price: "Liên hệ nhận giá tốt",
    image: "",
    images: [],
    badge: "Màn hình lớn",
    description: "Dành cho phòng khách rộng, nhu cầu xem phim, thể thao và giải trí gia đình với kích thước lớn.",
  },
  {
    id: "toshiba-43-compact",
    brand: "Toshiba",
    model: "Toshiba 43 inch",
    fullName: "Tivi Toshiba 43 inch đã kiểm tra",
    size: "43 inch",
    type: "Tivi cũ",
    condition: "Đã kiểm tra",
    warranty: "Bảo hành theo tình trạng máy",
    features: ["Kích thước gọn gàng", "Phù hợp phòng ngủ, phòng nhỏ", "Dễ lắp đặt"],
    oldPrice: "",
    price: "Giá đang cập nhật",
    image: "",
    images: [],
    badge: "Gọn gàng",
    description: "Kích thước linh hoạt cho phòng ngủ, phòng trọ hoặc không gian nhỏ cần giải pháp tiết kiệm diện tích.",
  },
  {
    id: "samsung-43u8500f",
    brand: "Samsung",
    model: "UA43U8500F",
    fullName: "Smart Tivi Crystal UHD Samsung 4K 43 inch UA43U8500F",
    size: "43 inch",
    type: "Tivi mới",
    condition: "Mới",
    warranty: "Bảo hành 2 năm",
    oldPrice: "",
    price: "7.700.000đ",
    badge: "Bảo hành 2 năm",
    description: "Smart Tivi Crystal UHD Samsung 4K 43 inch UA43U8500F phù hợp cho phòng khách, phòng ngủ hoặc không gian giải trí gia đình. Thiết kế hiện đại, hình ảnh sắc nét, dễ sử dụng và được Anh Minh Store tư vấn tận tình.",
    overview: [
      {
        paragraphs: [
          "Smart Tivi Crystal UHD Samsung 4K 43 inch UA43U8500F mang đến hình ảnh 4K chi tiết, vận hành mượt trên nền tảng Tizen™ và hỗ trợ điều khiển giọng nói Bixby tiếng Việt tiện lợi.",
        ],
      },
      {
        heading: "Thiết kế",
        paragraphs: [
          "Màn hình 43 inch gọn gàng, dễ bố trí trong nhiều không gian từ phòng khách vừa, phòng ngủ đến căn hộ nhỏ. Viền mỏng tạo cảm giác hình ảnh tràn viền, chân đế nhựa chắc chắn, thuận tiện khi đặt trên kệ tivi hoặc bàn.",
        ],
      },
      {
        heading: "Công nghệ hình ảnh",
        paragraphs: [
          "Tivi trang bị bộ xử lý Crystal 4K, tivi nâng cấp chất lượng hiển thị của nội dung thường lên gần chuẩn 4K. Công nghệ HDR10+ và Contrast Enhancer tăng chiều sâu cho khung hình, trong khi UHD Dimming tinh chỉnh độ sáng tối chi tiết hơn.",
        ],
      },
    ],
    specifications: [
      {
        group: "Tổng quan",
        rows: [
          { label: "Loại Tivi", value: "Smart Tivi Crystal UHD" },
          { label: "Kích cỡ màn hình", value: "43 inch" },
          { label: "Độ phân giải", value: "4K (Ultra HD)" },
          { label: "Loại màn hình", value: "Đèn nền LED viền (Edge LED)" },
          { label: "Hệ điều hành", value: "Tizen™" },
          { label: "RAM", value: "Hãng không công bố" },
          { label: "ROM (Bộ nhớ lưu trữ)", value: "Hãng không công bố" },
          { label: "Chất liệu chân đế", value: "Nhựa" },
          { label: "Chất liệu viền tivi", value: "Nhựa" },
          { label: "Nơi sản xuất", value: "Việt Nam" },
          { label: "Năm ra mắt", value: "2025" },
          { label: "Hãng", value: "Samsung" },
        ],
      },
      {
        group: "Công nghệ hình ảnh",
        rows: [
          { label: "Công nghệ hình ảnh", value: ["Độ tương phản cao - Mega Contrast", "HDR10+", "HDR", "Kiểm soát đèn nền UHD Dimming", "Công nghệ Color Booster", "Nâng cấp độ tương phản Contrast Enhancer", "4K Upscaling", "Chuyển động mượt Motion Xcelerator"] },
          { label: "Bộ xử lý", value: "Bộ xử lý Crystal 4K" },
          { label: "Tần số quét thực", value: "50 Hz/60 Hz" },
        ],
      },
      {
        group: "Tiện ích",
        rows: [
          { label: "Điều khiển tivi bằng điện thoại", value: "SmartThings" },
          { label: "Điều khiển bằng giọng nói", value: "Tìm kiếm giọng nói trên YouTube bằng tiếng Việt, Bixby có tiếng Việt" },
          { label: "Chiếu hình từ điện thoại lên TV", value: "AirPlay 2" },
          { label: "Remote thông minh", value: "Điều khiển One Remote Control tích hợp Solar Cell Remote" },
          { label: "Kết nối ứng dụng các thiết bị trong nhà", value: "SmartThings" },
          { label: "Ứng dụng phổ biến", value: "YouTube, Netflix, FPT Play, TV 360, VieON" },
          { label: "Tiện ích thông minh khác", value: "Built in IoT Hub, Universal Gestures, Quick Remote" },
        ],
      },
      {
        group: "Công nghệ âm thanh",
        rows: [
          { label: "Tổng công suất loa", value: "20W" },
          { label: "Âm thanh vòm", value: "Âm thanh chuyển động theo hình ảnh OTS Lite" },
          { label: "Các công nghệ khác", value: "Adaptive Sound, Q-Symphony" },
        ],
      },
      {
        group: "Cổng kết nối",
        rows: [
          { label: "Kết nối Internet", value: "Wi-Fi, Cổng mạng LAN" },
          { label: "Kết nối không dây", value: "Bluetooth 5.3" },
          { label: "USB", value: "1 cổng USB A" },
          { label: "Cổng nhận hình ảnh, âm thanh", value: "3 cổng HDMI, có 1 cổng HDMI eARC (ARC)" },
          { label: "Cổng xuất âm thanh", value: "1 cổng eARC (ARC)" },
        ],
      },
      {
        group: "Thông tin lắp đặt",
        rows: [
          { label: "Kích thước có chân, đặt bàn", value: "Ngang 95.78 cm - Cao 60.9 cm - Dày 15.7 cm" },
          { label: "Khối lượng có chân", value: "6.6 kg" },
          { label: "Kích thước không chân, treo tường", value: "Ngang 95.78 cm - Cao 55.88 cm - Dày 7.63 cm" },
          { label: "Khối lượng không chân", value: "6.4 kg" },
        ],
      },
    ],
    features: [
      "Độ phân giải 4K UHD",
      "Công nghệ Crystal UHD",
      "Smart TV dễ sử dụng",
      "Kích thước 43 inch",
      "Phù hợp phòng khách và phòng ngủ",
      "Bảo hành 2 năm",
    ],
    image: "mặt trước tivi.jpg",
    images: [
      "mặt trước tivi.jpg",
      "mặt nghiêng trái tivi.jpg",
      "màu nghiêng phải tivi.jpg",
      "viền tivi.jpg",
    ],
  },
  {
    id: "samsung-43-tu7000-cu",
    brand: "Samsung",
    model: "UA43TU7000",
    fullName: "Samsung Smart TV 43 inch cũ đã kiểm tra",
    size: "43 inch",
    type: "Tivi cũ",
    condition: "Đã kiểm tra",
    warranty: "Bảo hành theo tình trạng máy",
    oldPrice: "",
    price: "Liên hệ nhận giá tốt",
    badge: "Tivi cũ đẹp",
    description: "Samsung Smart TV 43 inch đã qua sử dụng, được kiểm tra hình ảnh và âm thanh trước khi tư vấn cho khách hàng.",
    features: ["4K UHD", "Smart TV", "Đã kiểm tra hình ảnh", "Đã kiểm tra âm thanh"],
    image: "",
    images: [],
  },
  {
    id: "lg-50-up7550-cu",
    brand: "LG",
    model: "50UP7550",
    fullName: "LG Smart TV 50 inch cũ đã kiểm tra",
    size: "50 inch",
    type: "Tivi cũ",
    condition: "Đã kiểm tra",
    warranty: "Bảo hành theo tình trạng máy",
    oldPrice: "",
    price: "Liên hệ nhận giá tốt",
    badge: "Còn đẹp",
    description: "LG Smart TV 50 inch đã qua sử dụng, phù hợp phòng khách vừa và được kiểm tra độ ổn định trước khi tư vấn.",
    features: ["4K UHD", "WebOS", "Hình ảnh ổn định", "Phù hợp phòng khách"],
    image: "",
    images: [],
  },
  {
    id: "sony-55-x80j-cu",
    brand: "Sony",
    model: "KD-55X80J",
    fullName: "Sony Google TV 55 inch cũ đã kiểm tra",
    size: "55 inch",
    type: "Tivi cũ",
    condition: "Đã kiểm tra",
    warranty: "Bảo hành theo tình trạng máy",
    oldPrice: "",
    price: "Liên hệ nhận giá tốt",
    badge: "Đáng tham khảo",
    description: "Sony Google TV 55 inch đã qua sử dụng, phù hợp nhu cầu xem phim, giải trí gia đình và được kiểm tra trước khi bán.",
    features: ["Google TV", "4K HDR", "Âm thanh rõ", "Tư vấn theo nhu cầu"],
    image: "",
    images: [],
  },
  {
    id: "toshiba-43-c350-cu",
    brand: "Toshiba",
    model: "43C350",
    fullName: "Smart Tivi Toshiba 4K 43 inch 43C350 đã qua sử dụng",
    size: "43 inch",
    type: "Tivi cũ",
    condition: "Đã kiểm tra",
    warranty: "Bảo hành theo tình trạng máy",
    oldPrice: "",
    price: "Liên hệ nhận giá tốt",
    badge: "Tivi cũ đã kiểm tra",
    description: "Smart Tivi Toshiba 4K 43 inch đã qua sử dụng, phù hợp phòng ngủ hoặc phòng khách nhỏ. Sản phẩm được kiểm tra hình ảnh, âm thanh và độ ổn định trước khi tư vấn.",
    features: [
      "4K UHD",
      "Smart TV",
      "Đã kiểm tra hình ảnh",
      "Đã kiểm tra âm thanh",
      "Phù hợp phòng ngủ"
    ],
    image: "",
    images: []
  },
  {
    id: "toshiba-55-c350-moi",
    brand: "Toshiba",
    model: "55C350",
    fullName: "Smart Tivi Toshiba 4K 55 inch 55C350",
    size: "55 inch",
    type: "Tivi mới",
    condition: "Mới",
    warranty: "Bảo hành 2 năm",
    oldPrice: "",
    price: "Liên hệ nhận giá tốt",
    badge: "Hàng mới",
    description: "Smart Tivi Toshiba 4K 55 inch phù hợp phòng khách, hỗ trợ trải nghiệm hình ảnh sắc nét, giao diện dễ sử dụng và nhiều tiện ích giải trí phổ biến.",
    features: [
      "4K UHD",
      "Smart TV",
      "Kích thước 55 inch",
      "Phù hợp phòng khách",
      "Bảo hành 2 năm"
    ],
    image: "",
    images: []
  }
 ];
