window.products = [
  {
    id: "samsung-55-du7000",
    brand: "Samsung",
    model: "UA55DU7000",
    size: "55 inch",
    type: "Tivi mới",
    condition: "Mới",
    features: ["4K UHD", "Smart TV", "Bảo hành chính hãng"],
    oldPrice: "",
    price: "Liên hệ nhận giá tốt",
    image: "",
    badge: "Hàng mới",
    description: "Phù hợp phòng khách, hình ảnh sắc nét, dễ sử dụng.",
  },
  {
    id: "lg-50-4k-uhd",
    brand: "LG",
    model: "LG 4K UHD 50 inch",
    size: "50 inch",
    type: "Tivi mới",
    condition: "Mới",
    features: ["Độ phân giải 4K UHD", "Hình ảnh sáng, màu sắc cân bằng", "Tư vấn theo diện tích phòng"],
    oldPrice: "",
    price: "Giá đang cập nhật",
    image: "",
    badge: "Tư vấn nhiều",
    description: "Lựa chọn phù hợp cho gia đình cần tivi 4K kích thước vừa, dễ bố trí trong phòng khách hoặc phòng sinh hoạt chung.",
  },
  {
    id: "sony-65-google-tv",
    brand: "Sony",
    model: "Sony Google TV 65 inch",
    size: "65 inch",
    type: "Tivi mới",
    condition: "Mới",
    features: ["Google TV tiện lợi", "Gợi ý cho không gian rộng", "Trải nghiệm giải trí phong phú"],
    oldPrice: "",
    price: "Liên hệ nhận giá tốt",
    image: "",
    badge: "Màn hình lớn",
    description: "Dành cho phòng khách rộng, nhu cầu xem phim, thể thao và giải trí gia đình với kích thước lớn.",
  },
  {
    id: "toshiba-43-compact",
    brand: "Toshiba",
    model: "Toshiba 43 inch",
    size: "43 inch",
    type: "Tivi cũ / mới theo tình trạng hàng",
    condition: "Liên hệ kiểm tra tình trạng",
    features: ["Kích thước gọn gàng", "Phù hợp phòng ngủ, phòng nhỏ", "Dễ lắp đặt"],
    oldPrice: "",
    price: "Giá đang cập nhật",
    image: "",
    badge: "Gọn gàng",
    description: "Kích thước linh hoạt cho phòng ngủ, phòng trọ hoặc không gian nhỏ cần giải pháp tiết kiệm diện tích.",
  },
  {
    id: "samsung-43u8500f",
    brand: "Samsung",
    model: "43U8500F",
    fullName: "Smart Tivi Crystal UHD Samsung 4K 43 inch",
    size: "43 inch",
    type: "Tivi mới",
    condition: "Mới",
    warranty: "Bảo hành 2 năm",
    oldPrice: "",
    price: "7.700.000đ",
    badge: "Bảo hành 2 năm",
    description: "Smart Tivi Crystal UHD Samsung 4K 43 inch 43U8500F phù hợp cho phòng khách, phòng ngủ hoặc không gian giải trí gia đình. Thiết kế hiện đại, hình ảnh sắc nét, dễ sử dụng và được Anh Minh Store tư vấn tận tình.",
    features: [
      "Độ phân giải 4K UHD",
      "Công nghệ Crystal UHD",
      "Smart TV dễ sử dụng",
      "Kích thước 43 inch",
      "Phù hợp phòng khách và phòng ngủ",
      "Bảo hành 2 năm",
    ],
    image: "mặt trước tivi.jpg",
    images: [
      "mặt trước tivi.jpg",
      "mặt nghiêng trái tivi.jpg",
      "màu nghiêng phải tivi.jpg",
      "viền tivi.jpg",
    ],
  },
];
